Dockerfile
docker-compose.dev.yml
docker-compose.setup.yml

Some tools (e.g. httpx) require gologger in version 1.0.1 and use the
the function gologger.Errorf, but in the Dockerfile the "-u" flag
instructs get to use the network to update the named packages and
their dependencies. Thus, gologger is updated to v1.1.2 where the
function gologger.Errorf seems to be removed (see #303).
The removal of the "-u" flag fixes the build error.

Fixed build error of httpx tool

---

dashboard/templates/dashboard/index.html
startScan/templates/startScan/history.html

This MR fixes a typo on the dashboard and the scan history. It should be 'Successful' with double s instead of 'Succesful' (https://www.dictionary.com/browse/successful).

Fix typo 'succesful' -> 'successful'

---

.github/workflows/build-pr.yml
.github/workflows/build.yml

Remove github actions deprecated set-env command: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Fix docker build with github actions

---

.github/SECURITY.md
startScan/templates/startScan/detail_vuln_scan.html

Fixed XSS on #347

---

reNgine/tasks.py

Randomizing UA for added protection from being easily blocked by a WAF/CDN or if a page returns a different status code depending on UA.
Currently it would be...
```
User-Agent: httpx - Open-source project (github.com/projectdiscovery/httpx)
```
Now it might be...
```
User-Agent: Mozilla/5.0 (Linux; U; Android 1.5; en-us; SPH-M900 Build/CUPCAKE) AppleWebKit/528.5  (KHTML, like Gecko) Version/3.1.2 Mobile Safari/525.20.1
```

Random UserAgent for HTTPX

---

web/scanEngine/static/scanEngine/js/custom_tools.js
web/scanEngine/templates/scanEngine/settings/tool.html
web/scanEngine/views.py

A security researcher nerrorsec reported an XSS on tool section, with specially crafted filename, you could inject the XSS payloads, which has now been fixed

Fixed XSS on Tool section

---

web/Dockerfile

- Starting in Go 1.17, installing executables with go get is deprecated. go install may be used instead. [Deprecation of 'go get' for installing executables](https://golang.org/doc/go-get-install-deprecation). 
- Install and update Go package with `go install -v example.com/cmd@latest` or `GO111MODULE=on go install -v example.com/cmd@latest`
- Add command to update Nuclei and Nuclei Templates

web/Dockerfile: Update Go to v1.17 and add command to update Nuclei & Nuclei Templates

---

web/reNgine/tasks.py

Here it causes the naabu scan results to be stored incorrectly.

Fix tasks.py

---

config/nginx/rengine.conf

The current `ssl_ecdh_curve` parameter value in `rengine.conf` causes a start failure for the proxy. With this new value, the proxy starts properly.

update ssl_ecdh_curve param

---

web/Dockerfile
web/requirements.txt

Update celery version to 5.2.7 in requirements.txt
Update go version to 1.20 in Dockerfile
These changes are required for install.sh to complete on Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-66-generic x86_64) (digital ocean droplet).
Note: Saw some warning/maybe error related to whatisport (or similar) pypi package. Will investigate at some point.

Fixes required to get install script working

---

docker-compose.yml

Remove duplicate networks mapping key from the docker-compose.yml in the `web` section

remove duplicate networks mapping key

---

web/reNgine/tasks.py

The "-json" option no longer works for Nuclei, it was changed to "-j".

Vulnerability scanning fix for Nuclei v2.9.1

---

web/api/serializers.py

@yogeshojha
I don't know why though. I went through the code, even searched for `uknown` but I guess it's being renamed somewhere else in the code, but then that'd have been picked up by my search too. So for some reason, something depends on `uknown`. Do you have any idea?
I confirmed by testing that this commit fixes the scanning.
ref: https://github.com/yogeshojha/rengine/commit/fd61c6b315b5aa15ac883940bc59e216829e069c

Hotfix: revert commit that broke scanning

---

web/reNgine/tasks.py

fix(port-scan): `int` object is not subscriptable

---

.gitignore

Bad security practice in case someone accidentally commits its environment variable, potentially exposing the URL, username and password. Example: https://github.com/yogeshojha/rengine/pull/742/files#r1171128911.

chore(`.gitignore`): add environment variable

---

update.sh

Before, when executing this script, it could cause conflict with local changes. For example, if a user has made any local changes, but executes `git pull`, then there will be conflicts which are not picked up by the script. Now, it asks the user whether the user wants its local changes being applied or not.
If yes, `make down && git stash save && git pull && git stash apply && make build && make up` is executed. This saves your local changes, updates reNgine, applies your changes again and then starts to build reNgine. If not, `make down && git stash && git stash drop && git pull && make build && make up` is executed. This stashes your changes, but deletes them after stashing. Then, reNgine is being updated and it then starts to build reNgine.

ops(`update.sh`): add choices

---

install.sh

Because the previous implementation was way too specific, it resulted in reNgine not installing on WSL environments in combination with Docker Desktop. That's why [even Docker recommends](https://docs.docker.com/config/daemon/troubleshoot/#check-whether-docker-is-running) executing the `docker info` command instead to see whether Docker is working and running.
Fixes #956.

ops(`install.sh`): fix reNgine not installing using WSL

---

web/reNgine/tasks.py

This PR prevents duplicate Nuclei vulns to be saved in subdomain database
A check is done before adding the vuln to the db
If it exists, saving is skipped
`record_exists` method could be used for others vulns check

Prevent duplicating Nuclei vulns for a subdomain

---

web/reNgine/common_func.py

Fix #1008 
I've added the scheme to prevent `urlparse` to fail and return empty string

Fix empty subdomain returned in nuclei scan

---

web/scanEngine/views.py

Fix report settings saving error
```
Exception Type: 	NoReverseMatch
Exception Value: 	Reverse for 'report_settings' with no arguments not found. 1 pattern(s) tried: ['scanEngine/(?P<slug>[-a-zA-Z0-9_]+)/report_settings$']
```

Add missing slug in report settings saving

---

web/reNgine/tasks.py

Fix #1001 
Tested and working
This PR should be rebased when my others PRs will be merged becaus tasks.py has been retouched a lot

Iterate over hostnames when multiple

---

web/reNgine/tasks.py
web/reNgine/utilities.py

Fix #999 
@yogeshojha Maybe we should implement the function `return_iterable` to all the join used to retrieve the config values from scanEngine config ?
It needs to be tested to prevent bad behaviour
This modification is tested and working

Fix nmap script ports iterable args

---

web/Dockerfile
web/fixtures/default_scan_engines.yaml
web/fixtures/external_tools.yaml
web/reNgine/tasks.py
web/scanEngine/templates/scanEngine/add_engine.html

Fix #997 
Add gau in renGine
Gauplus is always there but not in the default config.
Need a `make down && make up`
Fully tested & working

Gau install

---

web/startScan/templates/startScan/detail_scan.html
web/static/custom/custom.js

Fix #992 
- Popup
- Directory list

Fix dirfuzz base64 name display

---

web/targetApp/templates/target/summary.html

Fix #990 
I have duplicated the working code of the Scan tab and removed all the reference to `history.id` and `scan_id`
I've also added the event grouping listener
It could be good to create a sub template for this part (`$("#pills-subdomain-tab").click(function()`) that we can insert into the two template page, target ans scan, to prevent further problems.
The only changes in this part is the two **history** and **scan** vars that should be replaced by `null`
Code duplication needs more work

Fix target subdomains list v2

---

web/startScan/templates/startScan/detail_scan.html

Fix #909 
Popup not displaying with JS error
Add missing `=` in the `onclick` JS event

Fix file directory popup not showing in detailed scan

---

web/dashboard/templates/dashboard/index.html

Added the text:
> "Total Vulnerabilities discovered by reNgine across all targets, subdomains & endpoints."
To the tooltip icon on the Vulnerabilities Card on the Dashboard
How the label should be, following the same pattern as other tooltip labels:
On version 2.0.1 the tooltip label on the Total Vulnerabilities card is just a placeholder:

Added tooltip text to dashboard total vulnerabilities tooltip

---

web/targetApp/templates/target/summary.html

Target subdomain page blank due to the scan id set in the tab link.
On target page no scan id need to be set to get all the scan records
Tested and working

Fix no results in target subdomain list

---

web/targetApp/templates/target/summary.html

In my #991 PR i've forgotten a scan_id var modification.
I didn't saw the problem immediatly because scan_id and target_id have the same id.
Until the id is not the same, error will l not comes
PR fixes this problem

Fix subdomains list empty in Target

---

web/startScan/templates/startScan/detail_scan.html

Add directories count on Directories list

---

web/Dockerfile

There are some problems with Project Discovery tools
When installing tools, some are not up to date with the latest version.
The most important one is HTTPx, because scan can't start if no endpoint found.
1.3.6 has problems with `-asn` paramater that makes crash it
https://github.com/projectdiscovery/httpx/issues/1442
There's a lot of feedback on discord for this issue.
So it's important to have the most up to date Project Discovery tool when creating celery container.

Upgrade project discovery tool at CT build

---

web/startScan/templates/startScan/detail_scan.html

Reverts yogeshojha/rengine#1050 because it's part of 2.1.0, not 2.0.2.

Revert "Add directories count on Directories list"

---

web/startScan/static/startScan/js/detail_scan.js
web/startScan/templates/startScan/detail_scan.html
web/startScan/templates/startScan/vulnerabilities.html
web/targetApp/templates/target/summary.html
web/templates/base/_items/vulnerability_tab_content.html

Fix #1038 
Add a check to not load DT twice for subdomains and vulnerabilities.
Table config is really complex and it's the quickest way to fix this.
Also it doesn't need to load table on each tab click, so it saves a lot of bandwidth on huge project
I've add a reload button on the vulnerabilities table, like the one in subdomains.

Add a check to not load datatables twice

---

web/reNgine/tasks.py

While launching a port scan with Naabu + Nmap, I experienced a crash if Naabu returns no port
```
rengine-celery-1       | nmap                               | ERROR | 'NoneType' object is not subscriptable
rengine-celery-1       | Traceback (most recent call last):
rengine-celery-1       |   File "/usr/src/app/reNgine/celery_custom_task.py", line 129, in __call__
rengine-celery-1       |     self.result = self.run(*args, **kwargs)
rengine-celery-1       |   File "/usr/src/app/reNgine/tasks.py", line 1481, in nmap
rengine-celery-1       |     vulns = parse_nmap_results(output_file_xml, output_file)
rengine-celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/local.py", line 182, in __call__
rengine-celery-1       |     return self._get_current_object()(*a, **kw) …
```

Nmap port scan fails when Naabu return no port

---

.github/ISSUE_TEMPLATE/bug_report.yaml

This caused bug reports to not have an automatic label assigned.

chore(issue-templates): incorrect label name

---

web/api/views.py
web/startScan/static/startScan/js/detail_scan.js
web/startScan/templates/startScan/detail_scan.html
web/startScan/templates/startScan/subdomains.html
web/targetApp/templates/target/summary.html

In certain case, endpoints popup list is empty.
After research I saw that some url pointing to endpoint list miss the **project** parameter causing the base query which fetch the datas returns empty result
```
endpoints_obj = EndPoint.objects.filter(scan_history__domain__project__slug=project)
```
I've added some conditions to fit to the parameters possibilities and set the **project** parameter on all links
Endpoint display in all case well now

Endpoints list popup empty

---

web/reNgine/tasks.py

Related to #1041 
In database there is a lot of endpoints which does not have a target_domain_id value.
It generates a lot of duplicates and can cause scan to fail, bad count (see #1041) and a lot of side effects
This PR fix missing domain_id value while launching a subscan
This fix definitively #1040 
For those who wants to correctly count their endpoints previously scanned on target page, you need to update the target id of endpoints in the database
```sql
UPDATE public."startScan_endpoint"
set target_domain_id=1
where http_url like '%http_urls_to_update_here%'
```

Add missing domain id value in subscan

---

web/reNgine/settings.py

#971 has been closed and I forgot to publish the temporary fix for the [workaround I give](https://github.com/yogeshojha/rengine/issues/971#issuecomment-1764750542).
People report this issue on Discord, so we could publish this temporary fix until Django Celery Beat got updated
Details here
https://github.com/yogeshojha/rengine/issues/971#issuecomment-1764632134

Temporary fix to prevent celery beat crash

---

web/reNgine/tasks.py

Fix #1006 
I've added :
- a **try except** block to catch error on duplicate record returned by **get_or_create** in **saving_endpoint** method
- a **check** on endpoint existence in **dir_file_fuzz** method
Errors are logged to the console with the URL.
Tested and working
Now we need to find why there are duplicates endpoints in the db
But it's another issue

Fix crash on saving endpoint (FFUF related only)

---

web/reNgine/init.py

IOError has been deprecated in Python version 3.3: 
> EnvironmentError, IOError, WindowsError, VMSError, socket.error, select.error and mmap.error have been merged into OSError

IOError -> OSError

---

web/dashboard/templates/dashboard/admin.html
web/dashboard/views.py

1079 disallow empty password

---

web/Dockerfile

The installation method doesnt work on devices that arent amd64 as docker will choose a container architecture based on its host system architecture by default. this leads to compatability issues with arm systems and M1 macOS. This little change in the Dockerfile makes Docker emulate amd64 architecture and this way it works.
Tested on: ARM64 macOS, Arch Amd64

Update Dockerfile to fix silicon incompatability

---

web/startScan/models.py
web/startScan/views.py
web/templates/report/template.html

When **Ignore Informational Vulnerabilities** is checked there are still info vulns datas.
I've reworked the queries that display vulnerabilities to prevent info vulns to display in the :
- **Quick summary** Info blue box
- **Reconnaissance Findings**
- **Vulnerabilities Discovered** Info blue box
I've also fixed the **Vulnerabilities Discovered** listing by doing a correct loop through regrouped values because values withe the same path but not the same severity does not display well
Tested and working on current master branch

Fix report generation when `Ignore Informational Vulnerabilities` checked

---

.github/workflows/build-pr.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml

- updated checkout action to the newest version
- codeql version 1 actions were deprecated in january 2023, therefore updated to version 2

CI: update GitHub action versions

---

README.md
web/celery-entrypoint.sh
web/reNgine/settings.py

To track Error 500 and easily debug reNgine from the `make logs` command
To activate debug, from the root directory of reNgine :
1. Edit `web/entrypoint.sh` and add at the top `export DEBUG=1`
```sh
#!/bin/bash
export DEBUG=1
python3 manage.py migrate
python3 manage.py runserver 0.0.0.0:8000
exec "$@"
```
2. Restart the web container `docker-compose restart web`
3. To deactivate set **DEBUG** to **0** and restart  web container
Then, with **DEBUG** set to **1**, in the `make logs` output you could see the full stack trace to debug reNgine,.
Example with the tool arsenal version check API bug.
Now you know the real error `TypeError: run_command() got an unexpected keyword argument 'echo'`
And you can post it to the issue you can create to help developers to track the root cause and correct …

Add stack trace into make logs if DEBUG True

---

web/dashboard/templates/dashboard/admin.html

It's important for pentesters to know the differences between the roles, which is why I described the differences (from https://github.com/yogeshojha/rengine?tab=readme-ov-file#about-rengine) in a tooltip. I think using a tooltip is fine, or at least better than showing all of that text at once.
Unsure whether this should be part of 2.1.0 or 2.0.2.

feat(admin_settings): show role description users

---

web/reNgine/tasks.py

The code use_amass_config = config.get(USE_AMASS_CONFIG, False) retrieves the value associated with the key USE_AMASS_CONFIG from a configuration dictionary (config). If the key is not found, it defaults to False. The variable use_amass_config is then assigned this value.
Closes: https://github.com/yogeshojha/rengine/issues/1148

Fixed (subdomain_discovery | ERROR | local variable 'use_amass_config' referenced before assignment)

---

web/reNgine/init.py

`secrets` module has been introduced in Python 3.6, and its functions are inteded for cryptographic purposes, such as generating a random string securely as we do here.
Also using `_` as an empty placeholder since we don't do anything with the chars.

feat: update key generation function

---

.github/workflows/auto-comment.yml

* This will fix deprecation warnings in auto comment
* For github_token and Docker username and password I do not have enough permission But we can try these.
1. **Disable and re-enable the integration**: Go to the repository's settings, navigate to the "Integrations & services" (or similar) section, find the GitHub Actions integration, and disable it. Then, re-enable it again. This can help refresh the integration's access to the repository.
2. **Check repository permissions**: Ensure that the GitHub Actions integration has the necessary permissions to access the repository and perform the required actions. Make sure it has appropriate read and write access.
3. **Review workflow configuration**: Double-check your workflow file to ensure that it references the correct repository name and …

Update auto comment workflow due to deprecation warnings

---

docker-compose.dev.yml
docker-compose.yml
web/dashboard/templates/dashboard/index.html
web/templates/base/_items/top_bar.html
web/templates/base/login.html

This resulted in users continuing to be prompted that there's an update available.

chore: update version number to 2.0.3

---

default_yaml_config.yaml

Fix #1183 
Also I have checked the code to add all vars that was missing from major upgrade (1.3 -> 2.0)
I've put some hint on some values

Set and update default YAML config with all latest vars

---

web/reNgine/tasks.py
web/scanEngine/templates/scanEngine/settings/_items/external_tool_form.html

Fix #1010 
**TARGET** and **OUTPUT** are mandatory field but checks in code is not really accurate, so it generates error if one os this two placeholders is omitted
I've improved placeholders check in tasks
I've also added this information in the form page

Add checks for placeholder in custom tool task

---

web/celery-entrypoint.sh

Fix #984 
It's temporary until we decide what to do with deprecated whatportis
See discussion on #984

Whatportis - Replace purge by truncate to prevent port import error

---

web/reNgine/tasks.py

custom tool for subdomain scanning is failing as it is failing to find {TARGET} in the run command even if it is properly defined in the web portal.
checking the logs showed that line
```Python
if '{TARGET}' not in cmd:
```
failed as cmd was None.
cmd is used here to check required values but it is defined after this check.
```python
if '{TARGET}' not in cmd:
logger.error(f'Missing {{TARGET}} placeholders in {tool} configuration. Skipping.')
continue
if '{OUTPUT}' not in cmd:
logger.error(f'Missing {{OUTPUT}} placeholders in {tool} configuration. Skipping.')
continue
custom_tool = tool_query.first()
cmd = custom_tool.subdomain_gathering_command
cmd = cmd.replace('{TARGET}', host)
```
Thus, fixing the cmd variable initialisation.

Fix uninitialised variable cmd in custom_subdomain_tools

---

web/api/views.py
web/reNgine/common_func.py
web/reNgine/tasks.py

This code is resistant to command injection because it uses the `subprocess.run()` function with a list of arguments instead of a single-string command.
When you pass a list of arguments to a subprocess.run(), Python will not invoke a shell to execute the command. This means that shell metacharacters such as `;, &&, ||` etc., which could be used to inject additional commands, are treated as literal characters and not interpreted by the shell.
In this case, the URL variable is passed as a separate argument to the command, so even if it contains shell metacharacters, they will not be interpreted as such. This makes the command resistant to command injection attacks.
I have re-tested using the POC and it did not spawn the shell. However, I'd suggest performing a little more extensive test. …

[FIX] security: OS Command Injection vulnerability (x2) #1219

---

web/reNgine/tasks.py

Filter out OneForAll's CSV header row
Fixes #1243

Fix "subdomain" s3 bucket

---

web/targetApp/views.py

Worked on fixing the txt file upload so I can just get a bunch of domains and yeet it into this.

Fix Txt File Var Declaration

---

web/reNgine/common_func.py

python3 manage.py loadcustomengines
python3 manage.py dumpcustomengines
When using these functions the dumped/loaded custom engines format is not preserved. The new code now dumped the custom engines in the right format and when loading also.

Bug Correction: When dumping and loading customscanengines

---

web/reNgine/settings.py
web/requirements.txt

[django-environ](https://django-environ.readthedocs.io/) provides a clean interface to interact and cast settings from os.environ, allowing those to be replaced with a local `.env` file.
It also supports (my main reason to introduce it) `X_FILE` docker-like syntax, that will populate the enviornment variable `X` with the content of the file specified in `X_FILE`
Such as:
```yaml
environment:
PGPASSWORD_FILE: /run/secrets/pgpassword
```

use django-env

---

web/Dockerfile

The Docker image produced by the `master` branch currently is large: `5.91 GB`. Through some Docker optimizations this size can be reduced to 1/3 of that without losing any functionality.
```sh
$ docker images
REPOSITORY                                         TAG                  IMAGE ID       CREATED         SIZE
docker.pkg.github.com/yogeshojha/rengine/rengine   latest               41abe57a3889   9 minutes ago   5.91GB
```
```diff
-RUN wget https://golang.org/dl/go1.21.4.linux-amd64.tar.gz
-RUN tar -xvf go1.21.4.linux-amd64.tar.gz
-RUN rm go1.21.4.linux-amd64.tar.gz
-RUN mv go /usr/local
+RUN wget https://golang.org/dl/go1.21.4.linux-amd64.tar.gz && \
+    tar -xvf go1.21.4.linux-amd64.tar.gz go/bin/go --strip-components=2 && \
+    rm go1.21.4.linux-amd64.tar.gz && \
+    mv go …
```

Dockerfile cleanup: reduce image size 3x

---

web/api/views.py
web/targetApp/templates/target/add.html
web/targetApp/views.py

Importing CIDR blocks as targets was broken in a few different ways.
1. When adding CIDR targets via the multiple targets tab, there was a variable name collision that resulted in an infinite loop and memory leak being created which would quickly exhaust all memory on the system until the web process was killed. The name of the variable was changed from "ips" to "_ips" to correct this.
2. When adding a CIDR block via the resolve IP tab, the CIDR block was passed directly to gethostbyaddr(), which does not accept CIDR blocks, resulting in an error. This PR fixes that issue by expanding the CIDR block and passing each IP to gethostbyaddr(), and returning the domains for any which were resolved. This required a small API change to the IPToDomain API to send back a list of objects for each IP …

Fix importing CIDR blocks

---

certs/entrypoint.sh

This is necessary, since modern browsers expect the domain name in the SAN extension. Due to the fact that HSTS is used, one cannot access the web ui even if the cert is added to the system's truststore.
While signing the certificate, a subjectAltName (SAN) extension for the CN is added using a temporary configuration file which in the end gets removed.
Tested in a Digital Ocean droplet. Before the change, I was not able to access the web ui using Chrome or Firefox on my Mac.

Added SAN extension to the generated certs

---

web/startScan/static/startScan/js/detail_scan.js
web/static/custom/custom.js

fix xss on page title fix #1185

---

web/reNgine/tasks.py

Fixes Context key error on subdomain id
Fixes #1209, #1263

fix context key error #1263 #1209

---

web/reNgine/tasks.py

Fixes the screenshot CSV parsing issue

(bug) fix screenshot csv parser #1299

---

Makefile
make.bat

Docker compose v2 uses `docker compose` while earlier versions use `docker-compose`
@0xKayala reported that in Kali makefile script was not working. Likely due to older version of docker compose.
@calincoj mentioned replacing `docker compose` with `docker-compose` suggesting that older version is installed and rest of installation just works fine.
This PR checks for `docker compose` by default else uses `docker-compose`

Fix #1291 Refactor Makefiles for windows/linux to accomodate both v1 and v2 of docker compose

---

web/static/custom/custom.js
web/templates/base/base.html

A new feature has been added when clicked on the tabs inside scan results, will append the url hash on the browser. When the URL is accessed, the tab will be automatically clicked, which can be useful for navigation. 
Also, navigation inside tabs is added, for example when clicked on Subdomains tab, and then Screenshot tab, you can use back button to go back to Subdomains tab, earlier it would go back to the previous page and not previous tab.

Handle hash in url, added navigation for Tabs, Fixes #1155 bug href link with html id does not link to the expected url

---

docker-compose.dev.yml
scripts/uninstall.sh

reNgine uninstall script has been optimized to perform operations such as stopping the container, deleting the containers, and volumes that are only related to reNgine. This will also remove build cache objects related to reNgine intsllation.

Optimize uninstall scripts to perform operations only related to reNgine Fixes # 1187

---

web/reNgine/common_func.py
web/reNgine/utilities.py

Added validators to validate url before storing them into a txt file, a non standard url was stored into a file that was used while grabbing screenshot, this makes the entire scan fail. so validate urls before storing them in the alive file.

Added validators to validate URL fixes #1176

---

web/startScan/views.py

Typo in initiating periodic and clocked scan causes 500 error, this PR fixes the typo.

Fix slug while initiating periodic and clocked scan Fixes #1322

---

web/api/views.py

This PR addresses an issue in the tool update process where the `cd` command failed to execute properly. The problem was resolved by enabling shell execution in the subprocess call.
This error occurred because `cd` is a shell built-in command, not an executable file. By setting `shell=True`, we allow the use of shell built-ins like `cd`.
- Added `shell=True` parameter to the subprocess call in the `run_command` Celery task.

Fix error during tool update Fixes #1152

---

web/Dockerfile

Our Docker build was failing due to an error with setuptools. Specifically, we encountered a `ModuleNotFoundError: No module named 'setuptools.command.test'`. This was caused by issues with setuptools version 72.0.0, which was yanked from the repository by the package maintainers.
We've updated our Dockerfile to explicitly install setuptools version 72.1.0. This version resolves the issues present in 72.0.0 and allows our build process to complete successfully.

Upgrade setuptools to 72.1.0 to resolve installation error

---

web/reNgine/common_func.py

The current `get_domain_from_subdomain` function was not accurately handling all types of subdomains, especially those with less common or new TLDs. It also lacked proper validation for the returned domains.
This PR introduces a refactored `get_domain_from_subdomain` function that combines the strengths of `tldextract`, a custom fallback method.

(bug) Fix subdomain import for subdomains with suffix more than 4 chars Fixes #1128

---

web/reNgine/context_processors.py
web/reNgine/settings.py
web/templates/base/_items/footer.html
web/templates/base/base.html

This pull request removes the AWS external IP check that was previously executed on every page of reNgine. This check was implemented in the Django context preprocessor, causing it to run unnecessarily often and potentially impacting performance.
If the external IP information is still needed in specific areas of the application, we should implement a more targeted approach, fetching it only when necessary rather than on every page load. But fetching external IP on a webpage after its logged in doesn't make any sense.

Removes external IP from reNgine ui

---

web/Dockerfile

Already defined in:
https://github.com/yogeshojha/rengine/blob/20543d87cc57bb0184ff60adf2bd62b92c2c0faf/web/Dockerfile#L19-L26

remove redundant docker environment variables

---

web/Dockerfile

* Replace the use of `wget` and `tar` commands with a single `curl` command that pipes
directly to tar to streamline the installation process and reduce the number of
intermediate steps and potential points of failure.
* Add error handling for the `curl` command used to install Rust to ensure the script
stops on any errors during the download or installation process.

chores: Add error handling for the curl command

---

.github/workflows/auto-comment.yml
.github/workflows/build-pr.yml
.github/workflows/build.yml

This PR introduces several improvements to our GitHub Actions workflows, enhancing our CI/CD pipeline, build processes, and community interactions.
- Added support for multi-architecture builds (amd64, arm64, arm/v7)
- Implemented QEMU for cross-platform builds
- Removed Docker Hub login for PR builds to enhance security
- Added caching to improve build times
- Replaced third-party action with `actions/github-script` for more flexibility
- Implemented dynamic author mention in comments
- Adjusted build schedule to run every 5 days for proactive error detection
- Refined comment content for issues, PR openings, and PR closings

Update Github Actions Workflows

---

.github/workflows/auto-comment.yml
.github/workflows/build-pr.yml
.github/workflows/build.yml

Reverts yogeshojha/rengine#1375

Revert "chore: Release/2.1.3 Bump versions"

---

web/templates/report/template.html

TLDR; Added boolean operator to report template. This mitigates having a listed vulnerability with the "in" preposition, when no URL/URI is present.
When generating reports, if a reported vulnerability does not have a specific URL/URI, the report will generate according to the following syntax (regardless of whether the URL is present or not): 
`<Vulnerability name> in <URL>`
This often results in a report with vulnerability headings appearing incomplete like: WAF detected in 
This change updates template.html file with a conditional check, avoiding this issue.
Vulnerability headings without a URL omit the "in" preposition.

Update of template.html with conditional statement

---

web/startScan/templates/startScan/history.html
web/startScan/templates/startScan/schedule_scan_list.html
web/startScan/urls.py
web/startScan/views.py

This PR introduces the ability to delete multiple scheduled scans
Also introduces a loader in deleting multiple scans, both scheduled and normal ones

feat: feat ability to delete multiple scheduled scan #1360

---

web/reNgine/tasks.py
web/reNgine/utilities.py
web/startScan/templates/startScan/_items/schedule_scan_wizard.html
web/startScan/templates/startScan/_items/start_scan_wizard.html

This PR has improved system for checking out-of-scope subdomains in reNgine's subdomain discovery process. 
The new implementation supports both regex and plain text patterns.
> Introduced a new SubdomainChecker utility class
> Updated the subdomain discovery Celery task to use the new checker
> Updated the save_subdomain function to use new out of scope checker
> Supports both regex and plain text patterns

feat: Enhanced Out of Scope Subdomain Checking, Support for regex in out of scope scan parameter #1358 

---

web/startScan/static/startScan/js/start-scan-wizard-init.js
web/startScan/templates/startScan/_items/scanengine_accordion.html
web/startScan/templates/startScan/_items/start_scan_wizard.html
web/startScan/templates/startScan/history.html
web/startScan/views.py

This PR introduces prefilling scan parameters such as selecting the same scan engine used earlier, same imported subdomains, out-of-scope, paths, etc during rescan. This improved the user experience during the rescan of the same target

feat:  Prefll the scan parameters during rescan with the scan configuration values that were being used in earlier scan #1381 

---

CHANGELOG.md

On 29 August 2024, MITRE informed GitHub that CVE-2024-41661, which was issued August 2024 is a duplicate of CVE-2023-50094, which was issued December 2023 or January 2024. We rejected CVE-2024-41661 as a duplicate CVE because CVE-2023-50094 was published first. I suggest that the maintainers of reNgine replace all instances of CVE-2024-41661 with CVE-2023-50094, including in the changelog and repository security advisory.

Replace CVE-2024-41661 with CVE-2023-50094

---

scripts/uninstall.sh

TLDR; Script updated to abort uninstall process if anything other than the specified:  "y/Y/Yes/yes/YES" is entered. Fixes uninstall on user inputs like "no" or blank input.
____
The uninstall.sh script does not abort if any user input is provided.
Command used:
`sudo sh uninstall.sh`
The following user-input scenarios were tested, confirmed and fixed:
- no input
- "n" 
- "N"
- "No"
- "1"
- "q"
- "
- (
- '
- <
- [
- {
- /

Update of the uninstall.sh script

---

CHANGELOG.md

I previously saw `CVE-2024-41661` in the changelog and thought it needed to be changed to `CVE-2023-50094`. I should have noticed that version 2.1.3 fixes GHSA-96q4-fj2m-jqf7/`CVE-2024-43381`, not GHSA-fx7f-f735-vgh4/`CVE-2023-50094`. This commit refers to GHSA-96q4-fj2m-jqf7 by the correct CVE, `CVE-2024-43381`. I also corrected a minor capitalization typo on line 17.
My apologies for not noticing GHSA-96q4-fj2m-jqf7 and `CVE-2024-43381` before I submitted https://github.com/yogeshojha/rengine/pull/1393!

Version 2.1.3 contains a patch for CVE-2024-43381
