yogeshojha/rengine

dashboard/templates/dashboard/index.html
startScan/views.py

Fixes #36 and some dashboard UI changes

Fixes last scan date and dashboard UI enhancements

---

startScan/templates/startScan/start_scan_ui.html

checkbox set to required in start scan ui Fixed (#37)

---

dashboard/templates/dashboard/index.html

Added top margin to solve the issue #45

Grid spacing fixed #45

---

dashboard/templates/dashboard/index.html
startScan/templates/startScan/detail_scan.html

Fixed #45 grid spacing

---

startScan/templates/startScan/detail_scan.html
startScan/urls.py
startScan/views.py

Export subdomains and endpoints

Release 1.0.1

---

Dockerfile
README.md
startScan/templates/startScan/detail_scan.html
startScan/urls.py
startScan/views.py
tools/get_dirs.sh
tools/get_subdomain.sh
tools/get_urls.sh

Modified Readme
Added Workflow
Endpoint gathering from Hakrawler
Export HTTP urls

Hakrawler Featue Added

---

.gitattributes
CONTRIBUTORS.md

Fixed #81 by adding .gitattributes
https://github.com/dhoer/docker-on-windows-gotchas

Added gitattributes for lf issue fixes #81

---

startScan/templates/startScan/detail_scan.html

feature added clickable links Fixes  #74

---

Dockerfile
docker-compose.yml
docker-entrypoint.sh

python:3 and PostgreSQL has been migrated to their lightweight versions of alpine

Docker images migrated to more lightweight Alpine

---

CONTRIBUTORS.md
docker-entrypoint.sh

Json file did not exist and no default engines were created. Fixed it.

Updated Docker entrypoint

---

.env

Add dotenv file (fix namespace issues)

---

Dockerfile

Add netcat package + optimize package installation

---

startScan/templates/startScan/start_scan_ui.html

Floating button created. Fixes issue #73

implemented floating start_scan button

---

.github/SECURITY.md
README.md
reNgine/settings.py
startScan/templates/startScan/detail_scan.html
static/custom/custom.js

Fix for XSS issue in #178

---

Dockerfile

This edit fixes the error encountered for psycopg2 while building the project.

Fixing the psycopg2 error while building

---

targetApp/views.py

fixed new line issues for imported target

---

Dockerfile
reNgine/tasks.py

Hi,
I needed to exclude certain domains from a new engine during a scan. Let me know if you are interested in including this in the base repository.

FEATURE: exclude some subdomains in a new engine

---

Dockerfile
startScan/api/views.py
startScan/templates/startScan/detail_vuln_scan.html

Sorting Vulnerabilities by Severity by default

Sort Vulns by severity

---

startScan/templates/startScan/detail_scan.html

Added file size of files/directories found through dirsearch in 

---

reNgine/tasks.py

Fixed #384, #382 due to json obj error

Fixed #384, #382

---

docker-compose.yml
web/targetApp/static/targetApp/js/custom_domain.js
web/targetApp/templates/target/list.html

Fixed #424

---

web/tools/get_urls.sh

Fixed deep hakrawler issue

---

web/startScan/templates/organization/schedule_scan_ui.html
web/startScan/templates/startScan/schedule_scan_ui.html

Clocked Scan dropdown was not on firefox.

Fixed #476

---

docker-compose.dev.yml
docker-compose.yml
web/celery-entrypoint.sh
web/reNgine/tasks.py
web/scanEngine/views.py
web/startScan/templates/startScan/detail_scan.html

This was achieved by removing the first character i.e. '/' from the path var.

Fixed multiple issues/errors

---

README.md

Hi @yogeshojha ! As discussed, hope you don't mind adding a link to Reconmap from your repo. Thanks!

Add Reconmap link to related projects section

---

web/static/custom/custom.js

https://huntr.dev/bounties/da2d32a1-8faf-453d-8fa8-c264fd8d7806

Fixes HTML injection via Subscan feature

---

web/static/custom/right_sidebar.js

https://huntr.dev/bounties/6e2b7f19-d457-4e05-b2d5-888110898147

Fixes stored xss via Scan Engine Name

---

web/celery-entrypoint.sh

line 120 ~ 124  are same with line 126 ~130

Remove Duplicate Lines of wget ssrf_nagli.yaml

---

web/reNgine/common_func.py
web/reNgine/tasks.py

Added the proxy setting at the naabu_command

Fixed naabu proxy setting

---

CHANGELOG.md
docker-compose.dev.yml
docker-compose.yml
web/Dockerfile
web/dashboard/templates/dashboard/index.html
web/templates/base/_items/top_bar.html

fix nuclei issue #723,

---

web/startScan/templates/startScan/detail_scan.html

@yogeshojha Updated the Typo in OSINT page.

Fixed Typo in OSINT page

---

web/reNgine/common_func.py
web/startScan/templates/startScan/subscan_history.html

file : web/reNgine/common_func.py
when use whois lookup , will show this error : TypeError: expected string or bytes-like object
because re.xx(pattern，string，flag) , pattern is match to string , so need add str() function

fix whois look up ,regex error , please review it ~~

---

install.sh

This pull request does the following changes:
- Shows error message if installation failed
- Fixes showing success message even if installation failed

Fix success and error message printing

---

docker-compose.yml
web/Dockerfile
web/fixtures/external_tools.yaml
web/scanEngine/templates/scanEngine/settings/tool.html

- Add back alias for network
- Fix incorrect GitHub repo URL
Fixes #853, fixes #843

Fix installation issues when using Docker Compose

---

README.md
update.sh

It's much faster if you're not used to the commands, and especially if you need to do this regularly. It can save you time.
_Sidenote: this branch has been based on the branch I used for https://github.com/yogeshojha/rengine/pull/844, to prevent merge conflicts_

Add update script

---

README.md

I've reworded quite a lot of stuff. But because you wrote it from a personal experience/view, I can understand if you wouldn't be accepting the PR. Feel free to make any adjustments you'd like.
Fixes #847

docs(readme): improve grammar

---

web/targetApp/templates/target/summary.html

Add the missing lightbox libs on the target page
Fixes #947

Add missing lightbox css & js on target page

---

web/scanEngine/templates/scanEngine/settings/tool_arsenal.html
web/scanEngine/views.py
web/templates/base/_items/top_bar.html

Prevent Error 500 and saving problem

Add all the missing slug in scanEngine view & other places

---

web/startScan/urls.py
web/startScan/views.py
web/targetApp/templates/organization/list.html
web/targetApp/templates/target/list.html

Fix #982 
Add project slug to correctly display Schedule page

Add missing slug parameter in schedule scan

---

web/scanEngine/views.py

fix(notification_settings): submitting results in error 502

---

docker-compose.dev.yml
docker-compose.yml

Seems it was forgotten when bumping version in git

Bump rengine version to 2.0.1

---

web/dashboard/templates/dashboard/index.html
web/templates/base/_items/top_bar.html
web/templates/base/login.html

Related: https://github.com/yogeshojha/rengine/pull/1019

fix(versioning): bump version number to 2.0.1

---

scripts/uninstall.sh

- [ops(uninstall.sh): add missing volumes](https://github.com/yogeshojha/rengine/pull/977/commits/eeb214436567ce490caad7e6043bc4bc80ea1e7f)
- [ops(uninstall.sh): add echo messages](https://github.com/yogeshojha/rengine/pull/977/commits/52a0760d6058e3cf7419f56071fca08c4ba43a3e)

ops(`uninstall.sh`): add missing volumes and echo messages

---

web/api/views.py
web/dashboard/views.py

Fix endpoints list and count

---

web/api/serializers.py

Fix failing visualization when dorks are present

---

web/startScan/static/startScan/js/detail_scan.js
web/targetApp/templates/target/summary.html

Fix note not saving

---

web/api/serializers.py

Count only not done todos in subdomains list

---

web/reNgine/definitions.py

Fix bad copy/paste that made scan engine user agent parameter not working

Fix user agent definition keyword

---

web/Dockerfile
web/dashboard/views.py
web/scanEngine/templates/scanEngine/lookup.html

Fixes
- Fix Dashboard redirection error (fixes #1026)
- Fix Message color (red created confusing message as error) (fixes #1027)
- Update nuclei for v3, and nuclei v3 requires go 1.21. (fixes #1033) https://github.com/projectdiscovery/nuclei#install-nuclei

Fixes for #1033, #1026, #1027

---

web/startScan/templates/startScan/detail_scan.html

Add directories count on Directories list

---

web/scanEngine/models.py

fix attribute error on scan history #1103

---

web/targetApp/forms.py

issue-633: added already-in-org filter to target dropdown in org form

---

Makefile
install.sh
make.bat

**EDIT:** apparently, according to `make logs`, migrations are already applied after installing, I don't know how/why. Haven't searched for that specific piece of code. I'll however keep the command, if someone wants to migrate manually.
@yogeshojha Can I please get some feedback regarding the above before merge?
If anyone knows how to execute `make migration` right away in the `install.sh`, let me know. I tried multiple things, but it resulted in Python errors. If `make migrate` was executed, it worked. This is merely a workaround.
```bash
Applying targetApp.0020_auto_20220617_0552...Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: …
```

ops(migrations): add `make migrate` command

---

web/reNgine/context_processors.py
web/reNgine/settings.py
web/templates/base/_items/footer.html
web/templates/base/_items/top_nav.html
web/templates/base/base.html

Add external IP at bottom

---

web/celery-entrypoint.sh
web/reNgine/tasks.py

Drop infoga

---

install.sh

Fix a minor mistake in `install.sh`.

Fix grammatical mistake

---

web/targetApp/templates/target/summary.html

Fix subdomains list empty in Target

---

web/static/custom/custom.css

Fix top menu text overflow in low resolution

---

web/reNgine/settings.py

Change Redirect URL after login to prevent 500 error

---

web/targetApp/templates/target/list.html

Fix #1030 
Added the missing slug in link

fix-1030: Add missing slug on target summary link

---

.github/workflows/auto-comment.yml
.github/workflows/codeql-analysis.yml
docker-compose.dev.yml
docker-compose.yml
web/dashboard/templates/dashboard/index.html
web/reNgine/settings.py
web/static/custom/custom.css
web/targetApp/templates/target/list.html
web/targetApp/templates/target/summary.html
web/templates/base/_items/top_bar.html
web/templates/base/login.html

update codeql to v3

---

.github/workflows/auto-comment.yml
docker-compose.dev.yml
docker-compose.yml
web/api/views.py
web/dashboard/templates/dashboard/index.html
web/reNgine/settings.py
web/reNgine/tasks.py
web/reNgine/utilities.py
web/scanEngine/views.py
web/static/custom/custom.css
web/targetApp/forms.py
web/targetApp/templates/target/list.html
web/targetApp/templates/target/summary.html
web/templates/base/_items/top_bar.html
web/templates/base/login.html

replace .format() with f-strings

---

.github/workflows/auto-comment.yml
docker-compose.dev.yml
docker-compose.yml
web/dashboard/templates/dashboard/index.html
web/reNgine/common_func.py
web/reNgine/settings.py
web/static/custom/custom.css
web/targetApp/templates/target/list.html
web/targetApp/templates/target/summary.html
web/templates/base/_items/top_bar.html
web/templates/base/login.html

- remove unused uuid library
- remove non-existet params from function docstrings
- use f-strings instead of .format()
- simplify get_nmap_cmd() according to TODO block (tested)
- simplify xml2json() with context manager and remove unnecessary json functions (tested)

Optimize common funcs

---

web/reNgine/context_processors.py
web/tests/test_nmap.py

- remove unused libs
- remove unused exception var

small python cleanup

---

README.md

Fixed a broken link going to the detailed install instructions page

Update README.md | Fixed 1 broken link to the regine.wiki

---

README.md
default_yaml_config.yaml
web/Dockerfile
web/fixtures/default_scan_engines.yaml
web/scanEngine/templates/scanEngine/add_engine.html

remove duplicate gospider references

---

CHANGELOG.md
docker-compose.dev.yml
docker-compose.yml
web/dashboard/templates/dashboard/index.html
web/templates/base/_items/top_bar.html
web/templates/base/login.html

fix version

---

docker-compose.yml

added restart: always to redis container

---

.github/workflows/auto-comment.yml

PR #71 moved the location of the contribution guidelines. This PR adjusts sources to changes.

Update contribution guidelines reference

---

web/static/custom/custom.js

Fixes XSS on Vulnerability Description #1262

fix xss on vulnerability description payloads #1262

---

web/reNgine/common_func.py
web/reNgine/settings.py
web/reNgine/tasks.py
web/startScan/views.py

Fixes for Clocked and Periodic Scans Fix #1287 Fixes #1015

---

web/scanEngine/templates/scanEngine/settings/tool.html
web/scanEngine/views.py

This feature will allow uploading of multiple json files for GF patterns

Feature: Allow uploading of multiple gf patterns #1318

---

web/api/views.py
web/reNgine/settings.py
web/startScan/templates/startScan/history.html
web/startScan/templates/startScan/subscan_history.html
web/startScan/urls.py
web/startScan/views.py
web/static/custom/custom.js

This feature adds option to disable multiple scans

Feature: Introduce stop multiple scans #1270

---

web/static/custom/update.js
web/templates/base/base.html

This will showcase the latest features about reNgine using our wiki page, this will demonstrate what new feature has been added with visual representation so that the features don't go unnoticed.
A new data attribute has also been added to get this release version number

Show what's new popup when update happens and new features are released #1395 

---

web/api/views.py
web/targetApp/templates/organization/list.html

This PR will enable deleting multiple organizations

feat: Add ability to delete multiple organizations

---

web/celery-entrypoint.sh

This improves celery command generation and removal of watchmedo in production

bug: remove watchmedo usage in production #1419

---

web/api/views.py
web/reNgine/database_utils.py

This PR will allow one to create organization while quick adding the target via quick add modal

feat: Create organization when quick adding targets #492

---

web/dashboard/views.py

Quickfix for release 2.2.0
Fixes both #1426 and #1427

fix onboarding error when hackerone keys are not set
